# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Alex Arévalo Arenas"
description: "Game Development Portfolio"
author:      "Alex Arévalo Arenas"

sass:
  style: compressed # or expanded
  sass_dir: _sass    # Make sure this points to where your partials live