#-------------------------------
# General Site Settings

menu:
- {name: 'Portfolio', url: ''}
#- {name: 'Projects', url: 'projects'}
#- {name: 'Blog',     url: 'blog'}
- {name: 'About',    url: 'about'}
#- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'Nuevas Vistas',   url: 'nuevas-vistas', tags: 'Game', role: 'Solo', year: '2026'}
- {name: 'K-boom',   url: 'k-boom', tags: 'Game', role: 'Solo', year: '2025'}
- {name: 'Article: Theatrical resource inheritance in Pathologic 2',   url: 'article', tags: 'Research', role: 'Solo', year: '2025'}
- {name: 'Goblinmancer',   url: 'goblinmancer', tags: 'Game', role: 'Lead Game Designer & Audio Designer', year: '2025'}
- {name: 'Audio Reel',   url: 'audio', tags: 'Audio', role: 'Solo', year: '2025'}
- {name: 'Narrative Anthology',   url: 'narrative', tags: 'Narrative', role: 'Solo', year: '2024'}
- {name: 'Refugio 101',   url: 'refugio101', tags: 'Audio', role: 'Solo', year: '2025'}
- {name: 'Growing Fear',   url: 'growing-fear',tags: 'Game', role: 'Solo', year: '2023'}
- {name: 'Splintered Heaven', url: 'splintered-heaven',tags: 'Game', role: 'Solo', year: '2025'}
- {name: 'Prop Trip',  url: 'prop-trip',tags: 'Game', role: 'Solo', year: '2024'}
- {name: 'Mini Mobile Adventure',  url: 'mini-mobile-adventure',tags: 'Game', role: 'Solo', year: '2023'}
- {name: 'BFF!',   url: 'bff', tags: 'Game', role: 'Solo', year: '2023'}

#-------------------------------
# Contact Section

social:
#- {icon: 'twitter',   link: 'https://twitter.com/paululele'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'github',    link: 'https://github.com/AlexArevaloArenas'}
- {icon: 'linkedin',  link: 'https://www.linkedin.com/in/alejandro-arevalo-'}
- {icon: 'envelope',  link: 'mailto:mailto:alejandro.arevalo.arenas@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
